export enum ActionTypes {
  INCOMING_INVITE = 'INCOMING_INVITE',
  ACCEPT_INVITE = 'ACCEPT_INVITE',
  ACCEPT_INVITE_SUCCESS = 'ACCEPT_INVITE_SUCCESS',
  DECLINE_INVITE = 'DECLINE_INVITE',
  CLEAN_INVITE = 'CLEAN_INVITE',
}
