export enum ActionTypes {
  STARTUP = 'STARTUP',
  LOGOUT = 'LOGOUT',
  CLEAN_APP = 'CLEAN_APP',
  LOGIN = 'LOGIN',
  ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS',
  ON_LOGIN_ERROR = 'ON_LOGIN_ERROR',
  SET_APP_VERSION = 'SET_APP_VERSION',
  NEW_APP_VERSION = 'NEW_APP_VERSION',
  CLEAN_NEW_APP_VERSION = 'CLEAN_NEW_APP_VERSION',
}
