export enum ActionTypes {
  CLEAN_FRIEND = 'CLEAN_FRIEND',
  ADD_FRIEND = 'ADD_FRIEND',
  ON_ADD_FRIEND_SUCCESS = 'ON_ADD_FRIEND_SUCCESS',
  ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR',
  DELETE_FRIEND = 'DELETE_FRIEND',
  ON_DELETE_FRIEND_SUCCESS = 'ON_DELETE_FRIEND_SUCCESS',
}
