export enum ActionTypes {
  CLEAN_FRIEND = 'CLEAN_FRIEND',
  ADD_FRIEND = 'ADD_FRIEND',
  ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR',
  ON_ADD_FRIEND_SUCCESS = 'ON_ADD_FRIEND_SUCCESS',
  DELETE_FRIEND = 'DELETE_FRIEND',
  ON_DELETE_FRIEND_SUCCESS = 'ON_DELETE_FRIEND_SUCCESS',
  UPDATE_FRIEND_STATUS = 'UPDATE_FRIEND_STATUS',
  UPDATE_FRIEND_STATUS_SUCCESS = 'UPDATE_FRIEND_STATUS_SUCCESS',
}
