export enum Colors {
  TRANSPARENT = 'transparent',
  ADRIATIC_SEA = '#006180',
  GABLE_GREEN = '#12232c',
  BABY_BLUE_EYES = '#a1caf1',
  ANCHORMAN = '#293941',
  BLUE_EYED_BOY = '#2676d0',
  FIREBRICK = '#b62020',
  HARD_COAL = '#646464',
  BLACK_SUEDE = '#434343',
  SMOKE_SCREEN = '#aeaeae',
  DUGONG = '#707070',
  DEEP_SLATE_OLIVE = '#162a10',
  PATCH_OF_LAND = '#1f4f16',
  BLUE_VELVET = '#0f6686',
  THUJA_GREEN = '#136207',
}

export enum LightColors {
  ACTIVITY_INDICATOR = Colors.GABLE_GREEN,
  BACKGROUND = Colors.ADRIATIC_SEA,
  // tabs
  TAB_BAR_ACTIVE_TINT_COLOR = Colors.GABLE_GREEN,
  TAB_BAR_INACTIVE_TINT_COLOR = Colors.BABY_BLUE_EYES,
  // text
  MAIN_TEXT = Colors.GABLE_GREEN,
  SECONDARY_TEXT = Colors.ANCHORMAN,
  LINK_TEXT = Colors.BLUE_EYED_BOY,
  ERROR_TEXT = Colors.FIREBRICK,
  CHOSEN_TEXT = Colors.BABY_BLUE_EYES,
  // buttons
  STATIC_BUTTONS = Colors.HARD_COAL,
  PRESSED_BUTTONS = Colors.BLACK_SUEDE,
  STATIC_SECONDARY_BUTTONS = Colors.SMOKE_SCREEN,
  PRESSED_SECONDARY_BUTTONS = Colors.DUGONG,
  BUTTONS_LOADER = Colors.TRANSPARENT,
  TRANSPARENT_BUTTONS = Colors.TRANSPARENT,
  // icons
  CHOSEN_ICON = Colors.DEEP_SLATE_OLIVE,
  EXIT_ICON = Colors.PATCH_OF_LAND,
  // modals
  MODAL_BACKGROUND = Colors.GABLE_GREEN,
  MODAL_CONTAINER_BACKGROUND = Colors.SMOKE_SCREEN,
  // inputs
  PLACEHOLDER_INPUT = Colors.ANCHORMAN,
  DISABLE_INPUT = Colors.BLACK_SUEDE,
  BACKGROUND_INPUT = Colors.BLUE_VELVET,
  ERROR_INPUT = Colors.FIREBRICK,
  TRANSPARENT_INPUT = Colors.TRANSPARENT,
  BORDER_INPUT = Colors.GABLE_GREEN,
  // toasts
  SUCCESS_BACKGROUND_TOAST = Colors.PATCH_OF_LAND,
}
