export enum Colors {
  TRANSPARENT = 'transparent',
  GABLE_GREEN = '#12232c',
  BABY_BLUE_EYES = '#a1caf1',
  BLUE_EYED_BOY = '#2676d0',
  FIREBRICK = '#b62020',
  BLACK_SUEDE = '#434343',
  SMOKE_SCREEN = '#aeaeae',
  DUGONG = '#707070',
  DEEP_SLATE_OLIVE = '#162a10',
  PATCH_OF_LAND = '#1f4f16',
  BLUE_VELVET = '#0f6686',
  WHITE = '#ffffff',
  MEATLOAF = '#633309',
  CHOCOLATE_PANCAKES = '#884000',
  GREEN = '#00FF00',
  RED = '#FF0000',
  INK_BLUE = '#0e516a',
  FIRMAMENT_BLUE = '#14323f',
  SEMI_TRANSPARENT = 'rgba(255, 255, 255, 0.5)',
  YELLOW = '#ffff00',

  // new
  YANKEES_BLUE = '#1C2A40',
  COUNTRY_BLUE = '#718098',
  COARSE_WOOL = '#161D29',
  EMPIRE_YELLOW = '#F6D102',
  FARM_STRAW = '#d0b348',
}

export enum LightColors {
  ACTIVITY_INDICATOR = Colors.COUNTRY_BLUE,
  BACKGROUND = Colors.YANKEES_BLUE,
  QRCODE_BACKGROUND = Colors.WHITE,
  FRIEND_LIST_ITEM_BACKGROUND = Colors.INK_BLUE,
  FRIEND_LIST_ITEM_BORDER = Colors.FIRMAMENT_BLUE,
  // tabs
  TAB_BAR_ACTIVE_TINT_COLOR = Colors.GABLE_GREEN,
  TAB_BAR_INACTIVE_TINT_COLOR = Colors.BABY_BLUE_EYES,
  // text
  MAIN_TEXT = Colors.WHITE,
  SECONDARY_TEXT = Colors.COARSE_WOOL,
  LINK_TEXT = Colors.BLUE_EYED_BOY,
  ERROR_TEXT = Colors.FIREBRICK,
  CHOSEN_TEXT = Colors.BABY_BLUE_EYES,
  // buttons
  STATIC_BUTTONS = Colors.EMPIRE_YELLOW,
  PRESSED_BUTTONS = Colors.FARM_STRAW,
  STATIC_SECONDARY_BUTTONS = Colors.SMOKE_SCREEN,
  PRESSED_SECONDARY_BUTTONS = Colors.DUGONG,
  BUTTONS_LOADER = Colors.TRANSPARENT,
  TRANSPARENT_BUTTONS = Colors.TRANSPARENT,
  ACCEPT_BUTTON = Colors.PATCH_OF_LAND,
  DECLINE_BUTTON = Colors.FIREBRICK,
  // icons
  CHOSEN_ICON = Colors.DEEP_SLATE_OLIVE,
  EXIT_ICON = Colors.PATCH_OF_LAND,
  WINNER_ICON = Colors.YELLOW,
  // modals
  MODAL_BACKGROUND = Colors.GABLE_GREEN,
  MODAL_CONTAINER_BACKGROUND = Colors.SMOKE_SCREEN,
  // inputs
  PLACEHOLDER_INPUT = Colors.COUNTRY_BLUE,
  DISABLE_INPUT = Colors.BLACK_SUEDE,
  BACKGROUND_INPUT = Colors.WHITE,
  ERROR_INPUT = Colors.FIREBRICK,
  TRANSPARENT_INPUT = Colors.TRANSPARENT,
  BORDER_INPUT = Colors.GABLE_GREEN,
  // toasts
  SUCCESS_BACKGROUND_TOAST = Colors.PATCH_OF_LAND,
  ERROR_BACKGROUND_TOAST = Colors.FIREBRICK,
  // cards
  CREATE_GAME_CARD_BACKGROUND = Colors.CHOCOLATE_PANCAKES,
  CREATE_GAME_CARD_BORDER = Colors.MEATLOAF,
  // indicators
  USER_STATUS_ONLINE = Colors.GREEN,
  USER_STATUS_OFFLINE = Colors.RED,
  // game
  READY = Colors.PATCH_OF_LAND,
  NOT_READY = Colors.FIREBRICK,
  BACKGROUND_READY_BTN = Colors.BLUE_VELVET,
}
